### ISSUE TITLE
How to get seed data

### ISSUE THREAD

**Issue by fakharimran77** [ariestaazalia/Virtual-Tour-using-Pannellum#1]
Hello,

the project at github does not have seed data.  Can you please tell how to populate the tables at the start?

**Comment by ariestaazalia** [comment]
Hello, thank you for your feedbacks.

Seeders already added on #fd1e92e5f116677adfcea6750d8cf1ac688d2421

**Comment by ariestaazalia** [comment]
Hello, thank you for your feedback.

Your issue has been updated on #[fd1e92e](https://github.com/ariestaazalia/Virtual-Tour-using-Pannellum/commit/fd1e92e5f116677adfcea6750d8cf1ac688d2421)
